export const pdfData = {
  "Name": "Abrar Nabil",
  "NAME_BN": "আব্রার নাবিল",
  "Father": "Md. Rahim",
  "Mother": "Mrs. Fatema",
  "Dob": "2002-05-10",
  "Gender": "MALE",
  "BloodGroup": "O+",
  "MaritalStatus": "MARRIED",
  "Religion": "Islam",
  "Caste": "Bengali",
  "Nationality": "Bangladeshi",
  "PhoneNumber": "017XXXXXXXX",
  "Email": "abrar@example.com",

  "Village": "Mohammadpur",
  "PostOffice": "Mohammadpur PO",
  "PostCode": "1207",
  "Thana": "Mohammadpur",
  "District": "Dhaka",
  "Country": "Bangladesh",
  "NID": "19901234567890",
  "PresentAddress": "House #123, Road #45, Mohammadpur, Dhaka",

  "SSCBoard": "Dhaka",
  "SSCInstitution": "ABC High School",
  "SSCYear": "2018",
  "SSCRoll": "123456",
  "SSCGpa": "5.00",
  "SSCSubject": "Science",
  "HSCBoard": "Dhaka",
  "HSCInstitution": "XYZ College",
  "HSCYear": "2020",
  "HSCRoll": "654321",
  "HSCGpa": "4.80",
  "HSCSubject": "Science",

  "GuardianName": "Md. Rahim",
  "GuardianOccupation": "Businessman",
  "GuardianMonthlyIncome": "50000",
  "GuardianRelation": "Father",
  "GuardianVillage": "Mohammadpur",
  "GuardianPostOffice": "Mohammadpur PO",
  "GuardianPostCode": "1207",
  "GuardianThana": "Mohammadpur",
  "GuardianDistrict": "Dhaka",
  "GuardianCountry": "Bangladesh",
  "GuardianNID": "19901234567890",
  "GuardianPhone": "017XXXXXXXX",

  "LegalGuardianName": "Mrs. Fatema",
  "LegalGuardianOccupation": "Housewife",
  "LegalGuardianIncome": "0",
  "LegalGuardianRelation": "Mother",
  "LegalGuardianVillage": "Mohammadpur",
  "LegalGuardianPostOffice": "Mohammadpur PO",
  "LegalGuardianPostCode": "1207",
  "LegalGuardianThana": "Mohammadpur",
  "LegalGuardianDistrict": "Dhaka",
  "LegalGuardianCountry": "Bangladesh",
  "LegalGuardianNID": "19909876543210",
  "LegalGuardianPhone": "018XXXXXXXX",

  "LocalGuardianName": "Mr. Karim",
  "LocalGuardianRelation": "Uncle",
  "LocalGuardianVillage": "Dhanmondi",
  "LocalGuardianPostOffice": "Dhanmondi PO",
  "LocalGuardianPostCode": "1209",
  "LocalGuardianThana": "Dhanmondi",
  "LocalGuardianDistrict": "Dhaka",
  "LocalGuardianCountry": "Bangladesh",
  "LocalGuardianNID": "19901122334455",
  "LocalGuardianPhone": "019XXXXXXXX",

  "Department": "Computer Science and Engineering",
  "Pogram": "BSc in CSE",
  "HallName": "Shahid Minar Hall",
  "StudyBreakCause": "Health Issues",
  "AlreadyAdmittedInstitutio": "None",
  "ApplicantEmployment": "Part-time Tutor",
  "Scholarships": "Merit-based Scholarship"
}


export const realPdf = {
  "NAME_BN": "আব্রার নাবিল",
  "Name": "Abrar Nabil",

  "Father": "Md. Rahim",
  "Mother": "Mrs. Fatema",

  "Department": "Computer Science and Engineering",
  "Pogram": "BSc in CSE",
  "HallName": "Shahid Minar Hall",

  "SSCBoard": "Dhaka",
  "SSCInstitution": "ABC High School",
  "SSCYear": "2018",
  "SSCRoll": "123456",
  "SSCGpa": "5.00",
  "SSCSubject": "Science",

  "HSCBoard": "Dhaka",
  "HSCInstitution": "XYZ College",
  "HSCYear": "2020",
  "HSCRoll": "654321",
  "HSCGpa": "4.80",
  "HSCSubject": "Science",

  "StudyBreakCause": "Health Issues",
  "AlreadyAdmittedInstitutio": "None",
  "ApplicantEmployment": "Part-time Tutor",

  "Dob": "2002-05-10",
  "Gender": "MALE",
  "MaritalStatus": "MARRIED",
  "Religion": "Islam",
  "Caste": "Bengali",
  "Nationality": "Bangladeshi",
  "PhoneNumber": "017XXXXXXXX",
  "Email": "abrar@example.com",
  "Scholarships": "Merit-based Scholarship",

  "Village": "Mohammadpur",
  "PostOffice": "Mohammadpur PO",
  "PostCode": "1207",
  "Thana": "Mohammadpur",
  "District": "Dhaka",
  "Country": "Bangladesh",
  "NID": "19901234567890",
  "PresentAddress": "House #123, Road #45, Mohammadpur, Dhaka",

  "GuardianName": "Md. Rahim",
  "GuardianOccupation": "Businessman",
  "GuardianMonthlyIncome": "50000",
  "GuardianRelation": "Father",
  "GuardianVillage": "Mohammadpur",
  "GuardianPostOffice": "Mohammadpur PO",
  "GuardianPostCode": "1207",
  "GuardianThana": "Mohammadpur",
  "GuardianDistrict": "Dhaka",
  "GuardianCountry": "Bangladesh",
  "GuardianNID": "19901234567890",
  "GuardianPhone": "017XXXXXXXX",

  "LegalGuardianName": "Mrs. Fatema",
  "LegalGuardianOccupation": "Housewife",
  "LegalGuardianIncome": "0",
  "LegalGuardianRelation": "Mother",
  "LegalGuardianVillage": "Mohammadpur",
  "LegalGuardianPostOffice": "Mohammadpur PO",
  "LegalGuardianPostCode": "1207",
  "LegalGuardianThana": "Mohammadpur",
  "LegalGuardianDistrict": "Dhaka",
  "LegalGuardianCountry": "Bangladesh",
  "LegalGuardianNID": "19909876543210",
  "LegalGuardianPhone": "018XXXXXXXX",

  "LocalGuardianName": "Mr. Karim",
  "LocalGuardianRelation": "Uncle",
  "LocalGuardianVillage": "Dhanmondi",
  "LocalGuardianPostOffice": "Dhanmondi PO",
  "LocalGuardianPostCode": "1209",
  "LocalGuardianThana": "Dhanmondi",
  "LocalGuardianDistrict": "Dhaka",
  "LocalGuardianCountry": "Bangladesh",
  "LocalGuardianNID": "19901122334455",
  "LocalGuardianPhone": "019XXXXXXXX"
}
